cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'
    
urlpatterns = [
    path('', views.cartView, name='cart'),
    path("checkout/", views.checkout, name='checkout'),
    path('add/', views.addToCart , name='add'),
    path('add/qty/', views.addToCartQty , name='addQty'),
    path('remove/', views.removeCartItems , name='removeAllItems'),
    path('delete/<int:product_id>/qty/<int:qty>', views.deleteCartItem , name='delete'),
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path("", views.HomeView.as_view(), name='home'),
    # path("<int:pk>/detail/", views.ProductDetailView.as_view(), name='detail')
    path("detail/<int:p_id>/", views.detail, name='detail'),
    path("detail/tag/<int:category_id>", views.tag_shop, name='tag'),
    path("shop/products/", views.ShopView.as_view(), name='shop'),
    # path("contact/", views.contact_view, name='contact')

]

cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class CardProduct(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='cart_products'
    )
    quantity = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.product.name)


class Cart(models.Model):
    products = models.ManyToManyField(CardProduct, related_name='products')
    total_quantity = models.PositiveIntegerField(default=0)
    total_price = models.PositiveIntegerField(default=0)

    def add(self,product_id,qty):
        product = Product.objects.get(id=product_id)
        price = product.price * qty
        self.products.create(
            product=product,
            quantity=qty,
            price=price
        )
        self.total_quantity += qty
        self.total_price += price
        self.save()
        return True
    #
    def deleteItem(self, product_id,qty):
        product = Product.objects.get(id=product_id)
        p_id = product.id
        for item in self.products.all():
            if item.product.id == p_id:
                item.delete()
        price = product.price * qty
        # self.products.remove(product)
        self.total_quantity -= qty
        self.total_price -= price
        self.save()
        return True

    def removeAllItems(self):
        self.delete()


    def __str__(self):
        return f"Cart = {self.id}"
    
class Order(models.Model):
    user = models.ForeignKey(User, verbose_name='Xaridor', on_delete=models.CASCADE, null=True)
    first_name = models.CharField('Ism familiya', max_length=100)
    phone = models.CharField('Telefon', max_length=50)
    email = models.EmailField()
    address = models.CharField('Manzil', max_length=80)
    products = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    payed = models.BooleanField("To'lov xolati", default=False)

    class Meta:
        verbose_name='Order'
        verbose_name_plural='Orders'
        ordering = ['-id']

    def __str__(self):
        return f"{self.first_name}"


class OrderItem(models.Model):
	user = models.ForeignKey(User, verbose_name='Xaridor', on_delete=models.CASCADE)
	products = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
	first_name = models.CharField('Ism', max_length=100)
	last_name = models.CharField('Familya', max_length=100)
	phone = models.CharField('Telefon', max_length=50)
	telegram_id = models.CharField('Telegram ID', max_length=50, blank=True)
	email = models.EmailField()
	state = models.CharField('Viloyat', max_length=80)
	address = models.CharField('Tuman', max_length=80)
	street = models.CharField("Ko'cha va uy manzili", max_length=150)
	postal_code = models.CharField('Pochta indeksi', max_length=50)
	payment_method = models.CharField("To'lov turi", max_length=50,)
	message = models.TextField("Qo'shimcha xabar", blank=True)
 
    

	payed = models.BooleanField("To'lov xolati", default=False)

	class Meta:
		verbose_name='Buyurtma Tovar'
		verbose_name_plural='Buyurtma Tovarlar'
		ordering = ['-id']

	def __str__(self):
		return f"{self.first_name}"

shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField("Name", max_length=50)
    slug = models.SlugField("*", max_length=50)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Categories"
        verbose_name_plural = "Category"


class BannerHeader(models.Model):
    banner = models.ImageField('Banner Rasmi', upload_to='images/banner/')
    title = models.CharField('Title', max_length=255)
    body = models.TextField('Body')
    footer = models.CharField('Footer', max_length=255)
    url = models.CharField('Url', max_length=40000)


class BannerBody(models.Model):
    banner = models.ImageField('Banner Rasmi', upload_to='images/banner/')
    title = models.CharField('Title', max_length=255)
    body = models.TextField('Body')
    footer = models.CharField('Footer', max_length=255)
    url = models.CharField('Url', max_length=40000)



class Colors(models.Model):
	COLORS = (
	('white','WHITE'),
	('black','BLACK'),
	('blue','BLUE'),
	('green','GREEN'),
	('yellow','YELLOW'),
	('red','RED'),
	('tomato','TOMATO'),
	('pink','PINK'),
	('teal','TEAL'),
	('brown','BROWN'),
	)
	color = models.CharField('Product Color', max_length=50, choices=COLORS)
	def __str__(self):
		return self.color

class Product(models.Model):
    COLORS = (
        ('white', 'WHITE'),
        ('black', 'BLACK'),
        ('blue', 'BLUE'),
        ('green', 'GREEN'),
        ('yellow', 'YELLOW'),
        ('red', 'RED'),
        ('tomato', 'TOMATO'),
        ('pink', 'PINK'),
        ('teal', 'TEAL'),
        ('brown', 'BROWN'),
    )
    name = models.CharField("Name", max_length=100)
    slug = models.SlugField("*", max_length=100)
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='products'
        )
    image = models.ImageField("Product image", upload_to='product_images/')
    price = models.PositiveIntegerField("Price", default=0)
    description = models.TextField("About product")
    in_stock = models.PositiveIntegerField("Count", default=1)
    colors = models.ManyToManyField(Colors, related_name="colors", null=True, blank=True)
    discount = models.CharField("Discount", max_length=10, blank=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = ["-id"]



# Product Images model
class ProductImages(models.Model):
	product = models.ForeignKey(Product,
		default=None,
		null=True,
		blank=True,
		on_delete=models.CASCADE,
		related_name='product_images')
	image = models.ImageField('SLider Image',
		upload_to='product_images/',
		blank=True, null=True,)

	def __str__(self):
		return self.product.name

	class Meta:
		verbose_name = 'Slider Images'
		verbose_name_plural = 'Slider Image'


class Contact(models.Model):
    message = models.TextField()
    name = models.CharField(max_length=255)
    email = models.EmailField()


    def __str__(self):
        return self.name

cart/forms.py
from django import forms
from .models import Order, OrderItem

class OrderForm(forms.ModelForm):
    """ Form to Order Product """

    class Meta:
        model = Order
        fields = '__all__'
        exclude = ('payed','user', 'products')
        widgets = {
        'messages':forms.Textarea(attrs={'rows':30,'cols':8}),
        'phone': forms.TextInput(attrs={'pattern': r'[0-9]{2}-[0-9]{3}-[0-9]{4}'})
        }

shop/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {
        'messages':forms.Textarea(attrs={'rows':9, 'cols':30, 'placeholder': 'Enter Message', 'class': 'form-control w-100'}),
        'name': forms.TextInput(attrs={'placeholder': 'Enter your name', 'class': 'form-control'}),
        'email': forms.TextInput(attrs={'placeholder': 'Enter your email', 'class': 'form-control'})
        }

cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.http import JsonResponse
from .models import Cart
from .forms import OrderForm
from telepot import Bot
bot = Bot("5116496220:AAHhBGJN_9FYTKx7gwHwW4hDFpQ7QFupBmg")
grID = "1060158414"

# Create your views here.

def cart_init(request):
    try:
        cart = Cart.objects.get(id=request.session.get('user_cart_id'))
    except:
        cart = Cart.objects.create()
        request.session['user_cart_id'] = cart.id
    return cart


def cartView(request):
    cart = cart_init(request)
    return render(request,"cart.html", {"cart":cart})


import json
def addToCart(request):
    # print(request)
    d = request.GET.get('data')
    data = json.loads(d)
    # print(data)
    product_id = data['product_id']
    quantity = data['count']
    cart = cart_init(request)
    for i in cart.products.all():
        print('Bu id', i.product.id)
        print('bu boshqa hisob', i.product)
        if i.product.id == product_id:
            price = i.product.price * 1
            i.quantity += 1
            i.price += price
            cart.total_quantity += 1
            cart.total_price += price
            i.save()
            cart.save()
            return JsonResponse({'success': 200})
        print('bu boshqa', i.quantity)
    # print('bu', cart.products.all())
    cart.add(product_id,quantity)
    status = {
        'default': 202
    }
    if cart:
        status['success'] = 200
    else:
        status['error'] = 400
    return JsonResponse({'success': 200})



def addToCartQty(request):
    d = request.GET.get('data')
    data  = json.loads(d)
    product_id = data['product_id']
    quantity = data['qty']
    cart = cart_init(request)
    for i in cart.products.all():
        if i.product.id == product_id:
            price = i.product.price * quantity
            i.quantity += quantity
            i.price += price
            cart.total_quantity += quantity
            cart.total_price += price
            i.save()
            cart.save()
            return JsonResponse({'success': 200})
    cart.add(product_id,quantity)
    status = {
        'default': 202
    }
    if cart:
        status['success'] = 200
    else:
        status['error'] = 400
    return JsonResponse(status)


def deleteCartItem(request,product_id,qty):
    cart = Cart.objects.get(id=request.session.get('user_cart_id'))
    cart.deleteItem(product_id,qty)
    return redirect('cart:cart')

def removeCartItems(request):
    cart = cart_init(request)
    cart.removeAllItems()
    return redirect('cart:cart')

def checkout(request):
    cart = cart_init(request)
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            us = request.user
            f = form.save(commit=False)
            f.products = cart
            f.user = us
            f.save()
            # message = f"""
            #         Xaridor Akkaunti : {f.user.username}\n\
            #         Xaridor Ismi : {f.first_name}\n\
            #         Xaridor Nomeri : {f.phone}\n\
            #         Xaridor Email : {f.email}\n\
            #         Xaridor Manzili : {f.address}\n\
            #         Xaridor Jami Hisob Kitob : ${f.products.total_price}\n
            #         Xaridor Jami Product Miqdori : donada {f.products.total_quantity}\n
            #         """
            # for item in cart.products.all():
            #     print('Bu image url', item.product.image.url)
            #     print('Bu product name', item.product.name)
            #     print('Bu product price', item.product.price)
            #     print('Bu product quantity', item.quantity)
            #     print('Bu product total price', item.price)
            #     message += f"""\n\
            #         Product Nomi : {item.product.name}\n\
            #         Product Narxi : ${item.product.price}\n\
            #         Product Miqdori : {item.quantity}\n\
            #         Product Jami Narxi : ${item.price}\n\
            #     """
            # bot.sendMessage("1060158414", message)
            # bot.sendMessage("1060158414", "Hey Check Your Admin Panel http://127.0.0.1:8000/super/admin/")
            cart = cart_init(request)
            cart.removeAllItems()
            return redirect('/')
    else:
        form = OrderForm()
    return render(request, "checkout.html", {"form": form, 'cart': cart})

shop/views.py
from django.shortcuts import render, redirect
# from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from .models import Product
from cart.models import Order
from django.core.paginator import Paginator
from .forms import ContactForm
import random
import json

# Create your views here.


class HomeView(ListView, LoginRequiredMixin):
    model = Product
    template_name = 'index.html'
    context_object_name = 'products'
    # queryset = Product.objects.all().select_related("category")[:8]

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     product = list(Product.objects.select_related("category").all().values())
    #     random_product = random.sample(product, 3)
    #     context["features"] = random_product
    #     return context

# class ProductDetailView(DetailView):
#     model = Product
#     template_name = 'product.html'
    

class ShopView(ListView):
    paginate_by = 6
    model = Product
    template_name = 'shop.html'
    context_object_name = 'products'
    queryset = Product.objects.all().select_related("category")

def detail(request, p_id):
    obj = Product.objects.select_related("category").get(id=p_id)
    category = obj.category
    related_product = Product.objects.filter(category=category)
    print(obj)
    context = {
        "object":obj,
        "products": related_product
    }
    return render(request, "detail.html", context)

def tag_shop(request, category_id):
    related_product = Product.objects.filter(category=category_id)
    paginator = Paginator(related_product, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'products': page_obj,
        'page_obj': page_obj, 
    }
    return render(request, "shop.html", context)


# def filter(request):
#     d = json.loads(request.GET['data'])
#     min_value = d['min_value']
#     max_value = d['max_value']
#     category_id = d['category_id']
#     data = {}
#     product = list(Product.objects.filter(price__range=(min_value, max_value), category=category_id).values())
#     data['data'] = product
#     print(data)
#     return JsonResponse(data)


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Shop</title>
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}

.card {
  padding-top: 12px;
  padding-bottom: 12px;
}

.buttons button {
  padding: 8px 18px;
  border: none;
  border-radius: 10px;
  background: darkgreen;
  color: #fff;
  margin-bottom: 10px;
}

.title {
  color: #000;
  text-decoration: none;
}

.image-content-hidden {
  width: 100%;
  height: auto;
  overflow: hidden;
}

.hoverabel-animation {
  transition: all 0.5s;
}

.hoverabel-animation:hover {
  transform: scale(1.3);
}

    </style>
    <!-- custom css -->
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    
      <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        <div class="container">



          <a class="navbar-brand" href="/">Online Shop Uz</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link text-light" href="/">Bosh Sahifa</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'store:shop' %}">Mahsulotlar</a>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Kategoriyalar
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for category in categories %}
                        <a class="dropdown-item" href="{% url 'store:tag' category.id %}">{{ category.name }}</a>
                    {% endfor %}
                </div>
              </li>

            </ul>
            <div class="cart-nav" style="margin-left: 20px;">
              <div class="text-light">
                <a href="{% url 'cart:cart' %}" class="text-light">
                  <i class="fas fa-shopping-cart"> <span class="item-count" style="visibility:hidden">0</span></i>
                </a>
                </div>
            </div>
          </div>
        </div>
      </nav>


      {% block content %}

      {% endblock %}

      <!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section
      class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
    >
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
  
      <!-- bootstrap bundle -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <!-- custom js -->
      <script src="/static/js/app.js"></script>
      <script>
function AddToCart(product_id){
  let d = {
      product_id: product_id,
      count: 1,
      }
  let data = JSON.stringify(d)
  if (window.XMLHttpRequest) {
    var xhttp=new XMLHttpRequest();
  } else {  // code for IE6, IE5
      var xhttp=new ActiveXObject("Microsoft.XMLHTTP");
  }
  xhttp.onreadystatechange = function() {
  if (xhttp.readyState === 4 && xhttp.status === 200) {
      var data = JSON.parse(this.responseText);
      if (data['success'] == 200) {
      }
      else {
          alert('Biror narsa hato ketdi')
      }
  }else{

    }
  }
  var url = "/cart/add/"
  xhttp.open("GET", url+`?data=${data}`, true);
  xhttp.send();
}
          let slide_active = document.querySelector('.slider_first');
          console.log(slide_active)
          slide_active.classList.add('active')
        //   let count = 0;
  //if add to cart btn clicked
  $('.cart-btn').on('click', function (){
    let cart = $('.cart-nav');
    let total_count = $('.item-count')[0].innerText;
    let total_count_int = parseInt(total_count)
    // console.log(total_count);
    // find the img of that card which button is clicked by user
    let imgtodrag = $(this).parent('.buttons').parent('.content').parent('.card').find("img").eq(0);
    if (imgtodrag) {
      // duplicate the img
      var imgclone = imgtodrag.clone().offset({
        top: imgtodrag.offset().top,
        left: imgtodrag.offset().left
      }).css({
        'opacity': '0.8',
        'position': 'absolute',
        'height': '150px',
        'width': '150px',
        'z-index': '100'
      }).appendTo($('body')).animate({
        'top': cart.offset().top + 20,
        'left': cart.offset().left + 30,
        'width': 75,
        'height': 75
      }, 1000, 'easeInOutExpo');
  
        $(".cart-nav .item-count").text(total_count_int+1);
  
      imgclone.animate({
        'width': 0,
        'height': 0
      }, function(){
        $(this).detach()
      });
    }
  });
      </script>
  </body>
  </html>

templates/cart.html
{% extends "base.html" %}
{% block content %}
<div class="section" style="background: #eee">
    <br>
    <br>
    <!-- container -->
    <div class="container">
       

        <!-- row -->
        <div class="row">
            <div class="col-12">
                <div class="card user-cart mt-3 p-3 w-100" style="overflow: auto;">

                    {% if cart.products.all.count != 0 %}

                    <div class="card-title">
                        <h3 style="float: left">Cart Items</h3>
                        <a href="{% url 'cart:removeAllItems' %}" class="btn btn-success" style="float: right">
                            Clear Cart
                        </a>
                    </div>
                    

                    <table class="table table-striped text-center">
                        <thead>
                            <tr>
                                <th>Tovar rasmi</th>
                                <th>Narxi</th>
                                <th>Miqdori</th>
                                <th>Jami Narxi</th>
                                <th>Harakat</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for product in cart.products.all %} {% with product as item %}
                            <tr>
                                <td>
                                    <img src="{{ item.product.image.url}}" width="50" height="auto" alt="No img">
                                </td>
                                <td>
                                    <strong>${{ item.product.price }}</strong>
                                </td>
                                <td>
                                    <b>{{ item.quantity }}</b>
                                </td>
                                <td>
                                    <b>${{ item.price }}</b>
                                </td>
                                <td>
                                    <a href="{% url 'cart:delete' item.product.id item.quantity  %}" class="h3">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endwith %} {% endfor %}
                            
                        </tbody>
                    </table>
                    <h4>Cart total : ${{ cart.total_price }}</h4>
                    <h4>Cart Items : {{ cart.total_quantity }}</h4>
                    <a class="btn w-50 btn-dark text-light" href="checkout/">Checkout</a>
                    {% else %}
                            <h3 class="text-center">Siz hali hech narsa olganingiz yoq !</h2>
                    {% endif %}
                </div>
            </div>

        </div>
        <br>
        <br>
        <br>
    </div>
</div>

<!--================End Cart Area =================-->
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<br>
<br>


  <!--================Checkout Area =================-->
  <section class="checkout_area section_gap">
    <div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="billing_details">
        <div class="row">
          <div class="col-lg-8">
            <h3>Billing Details</h3>
                {{ form|crispy }}
            <button class="btn btn-dark w-50 mt-3">Order</button>
          </div>
        </div>
      </div>
    </form>
    </div>
  </section>
  <!--================End Checkout Area =================-->

  <br>
  <br>
{% endblock %}